/**
 * Documentation figures (tools/figures/make.js): the committed SVGs in docs/figures/ must match a
 * fresh build, and every figure must be used by docs/THEORY.md and by the in-app Theory tab.
 *
 * Numbers are compared with a tolerance of 0.1 so that a last-digit rounding flip on another
 * platform cannot fail the test; any structural change (new element, changed text) fails it.
 * After changing the core or the figure code, run `deno task figures`.
 */
import { buildFigures, FIGURES } from "../tools/figures/make.js";
import { assert } from "./assert.js";

const root = new URL("../", import.meta.url);
const read = (path) => Deno.readTextFileSync(new URL(path, root));
const NUMBER = /-?\d+(?:\.\d+)?/g;

/** Compares two SVG sources: identical apart from numbers, numbers within `tol`. */
function sameSvg(a, b, tol = 0.1 + 1e-9) {
  if (a.replace(NUMBER, "#") !== b.replace(NUMBER, "#")) return "structure differs";
  const na = a.match(NUMBER) ?? [], nb = b.match(NUMBER) ?? [];
  for (let i = 0; i < na.length; i++) {
    if (Math.abs(Number(na[i]) - Number(nb[i])) > tol) return `number ${na[i]} vs ${nb[i]}`;
  }
  return "";
}

const built = buildFigures();

Deno.test("figures: committed SVGs match a fresh build (run `deno task figures`)", () => {
  for (const [name, svg] of Object.entries(built)) {
    let committed;
    try {
      committed = read(`docs/figures/${name}`);
    } catch {
      throw new Error(`docs/figures/${name} is missing`);
    }
    const diff = sameSvg(svg, committed);
    assert(diff === "", `docs/figures/${name} is out of date: ${diff}`);
  }
  const files = [...Deno.readDirSync(new URL("docs/figures/", root))].map((e) => e.name);
  for (const f of files) assert(f in FIGURES, `docs/figures/${f} is not generated by make.js`);
});

Deno.test("figures: well-formed, accessible, finite", () => {
  for (const [name, svg] of Object.entries(built)) {
    assert(/^<svg [^>]*viewBox="0 0 \d+ \d+"/.test(svg), `${name}: svg root with viewBox`);
    assert(/<title id="t">[^<]+<\/title>/.test(svg), `${name}: title`);
    assert(/<desc id="d">[^<]+<\/desc>/.test(svg), `${name}: description`);
    assert(!/NaN|Infinity|undefined/.test(svg), `${name}: no NaN/Infinity/undefined`);
    const open = (svg.match(/<g[ >]/g) ?? []).length, close = (svg.match(/<\/g>/g) ?? []).length;
    assert(open === close, `${name}: balanced groups`);
  }
});

Deno.test("figures: every figure appears in THEORY.md and in the Theory tab", () => {
  const theory = read("docs/THEORY.md"), panel = read("src/ui/theoryPanel.js");
  for (const name of Object.keys(FIGURES)) {
    assert(theory.includes(`(figures/${name})`), `THEORY.md embeds ${name}`);
    assert(panel.includes(`"${name}"`), `theoryPanel.js shows ${name}`);
  }
  for (const [, name] of theory.matchAll(/\]\(figures\/([^)]+)\)/g)) {
    assert(name in FIGURES, `THEORY.md references unknown figure ${name}`);
  }
});
