/**
 * @file theoryPanel.js — the "Theory" tab: live values at the selected yarn's fell point, then the
 * model in words, formulas (KaTeX) and figures. It follows docs/THEORY.md section by section and
 * uses the same figures (docs/figures/*.svg, generated by tools/figures/make.js) with the same
 * numbers. Formulas are rendered once; only the value table updates.
 */

import katex from "katex";
import {
  coverFactor,
  jammingAngle,
  quasiStaticAngle,
  quasiStaticConvergenceLength,
} from "../core/analysis.js";

const DEG = 180 / Math.PI;
/** Figures, relative to index.html (deployed next to it, see .github/workflows/deploy.yml). */
const FIGURE_DIR = "docs/figures/";
const THEORY_URL = "https://github.com/VaitkusM/braiding-applet/blob/main/docs/THEORY.md";

/**
 * Section content: [kind, ...payload] with kind
 *   "p"   paragraph (plain text),
 *   "f"   display formula (TeX),
 *   "fig" figure: [file name, number, alt text, caption].
 */
const SECTIONS = [
  {
    title: "How the model works",
    body: [
      [
        "fig",
        "overview.svg",
        0,
        "Flow of the model from the machine to the laid yarn",
        "The machine moves the guide points; the straight free yarn and a contact condition move the fell point; the geometry of the laid yarn follows in closed form.",
      ],
    ],
  },
  {
    title: "The braiding process",
    body: [
      [
        "fig",
        "machine-side.svg",
        1,
        "Side view of the machine and the convergence zone",
        "Reference case (16 carriers, r = 40 mm, Rg = 150 mm, α = 45°) in side view. Yarns run from the carriers through the guide ring to the fell line on the mandrel.",
      ],
      [
        "p",
        "N carriers revolve about the machine axis at ω, half of each family in either direction, weaving in and out of each other. Every yarn passes an idealised guide point G on the guide ring (radius Rg) and meets the mandrel at the fell line, a convergence length h downstream. The mandrel is taken up along its own axis at speed v.",
      ],
      [
        "f",
        String
          .raw`\varphi_{\pm}(t)=\varphi_{\pm,0}\pm\omega t,\qquad G(t)=R_g\,(\cos\varphi,\ \sin\varphi,\ 0)`,
      ],
      [
        "p",
        "The model works in the mandrel frame, where the laid yarn is at rest; there Ġ is the guide point's rotation plus the take-up.",
      ],
    ],
  },
  {
    title: "The fell-point model",
    body: [
      [
        "p",
        "The free yarn is a straight segment from G to the fell point F; deposited yarn sticks; there is no friction before contact (Kessels & Akkerman 2002). Contact is unilateral:",
      ],
      ["f", String.raw`g=(G-F)\cdot n(F)\ \ge\ 0`],
      [
        "fig",
        "contact-states.svg",
        2,
        "Pinned, tangent and wrapping contact states",
        "If g > 0 the fell point stays (tie ring, lift-off). If G moves so that the straight yarn would cut the mandrel, the yarn wraps: F advances along the free yarn until it is tangent again.",
      ],
      [
        "fig",
        "tangency-front.svg",
        3,
        "Free yarns tangent to the mandrel circle, seen along the axis",
        "Seen along the axis of a cylinder every free yarn is tangent to the mandrel circle, so F lags behind G by β with cos β = r/Rg.",
      ],
      [
        "p",
        "While wrapping, F moves along the free-yarn direction t, which is therefore also the tangent of the laid yarn: Ḟ = λt, with λ the laying rate. The configuration satisfies G = F + L t. Differentiating it with t′ = κg b − κn n gives the guide point's relative velocity in the Darboux frame (t, n, b = n × t) of the laid yarn:",
      ],
      [
        "f",
        String.raw`\dot G=(\lambda+\dot L)\,t+\lambda L\,\kappa_g\,b-\lambda L\,\kappa_n\,n`,
      ],
      [
        "fig",
        "darboux-frame.svg",
        4,
        "Darboux frame of the laid yarn at the fell point",
        "The free yarn leaves the fell point along t, the tangent of the laid yarn.",
      ],
      ["p", "Its three components give the laying rate and the curvatures in closed form:"],
      [
        "f",
        String
          .raw`\lambda=-\frac{\dot G\cdot n}{L\,\kappa_n},\quad \kappa_g=\frac{\dot G\cdot b}{\lambda L},\quad \kappa_n=-\frac{\dot G\cdot n}{\lambda L},\quad \frac{\kappa_g}{\kappa_n}=-\frac{\dot G\cdot b}{\dot G\cdot n}`,
      ],
      [
        "p",
        "The yarn is laid when G dives below the tangent plane on a surface that is convex along the yarn (κn > 0). The slip ratio depends only on the direction of Ġ in the normal plane of the yarn.",
      ],
      [
        "fig",
        "bridging-contact.svg",
        5,
        "Bridging over a dip and catching on a bulge",
        "Schematic. Where κn < 0 a taut yarn cannot follow the surface: it spans the stretch with a straight chord (BRIDGE), or catches on an obstacle rising into the free yarn (CONTACT).",
      ],
    ],
  },
  {
    title: "Braid angle and convergence length",
    body: [
      [
        "p",
        "If the fell point stayed fixed in the machine frame it would move over the mandrel with parallel speed ωr and meridian speed v√(1+r′²):",
      ],
      ["f", String.raw`\tan\alpha_{qs}=\frac{\omega r}{v\sqrt{1+r'^2}}`],
      [
        "p",
        "The exact relation on a centred mandrel involves the rates of the lag angle β and of the convergence length h:",
      ],
      ["f", String.raw`\tan\alpha=\frac{r\,(\omega-\dot\beta)}{(v-\dot h)\sqrt{1+r'^2}}`],
      [
        "p",
        "On a cylinder the lag is constant once the yarns wrap, and h relaxes exponentially (Du & Popper 1994):",
      ],
      [
        "f",
        String
          .raw`h(t)=h_\infty+(h_0-h_\infty)\,e^{-t/\tau},\qquad h_\infty=\frac{\sqrt{R_g^2-r^2}}{\tan\alpha},\qquad \tau=\frac{\sqrt{R_g^2-r^2}}{\omega r}`,
      ],
      [
        "fig",
        "transient-cylinder.svg",
        6,
        "Convergence length after start-up on the reference cylinder",
        "Pinned on the tie ring, h grows with the take-up; once the yarns are tangent it relaxes to h∞ as Du and Popper predict.",
      ],
      [
        "p",
        "The fell point advances over the mandrel at about v, so the decay length along the braid is vτ = h∞: the braid needs roughly one convergence length to adapt to a new radius.",
      ],
      [
        "fig",
        "lag-taper.svg",
        7,
        "Braid angle along the default taper: simulated, quasi-static and geodesic",
        "Default taper: the simulated braid angle trails the quasi-static value through the transition; the geodesic from z = 250 mm turns the other way.",
      ],
    ],
  },
  {
    title: "Curvature seen by a yarn",
    body: [
      [
        "p",
        "Curvatures are convex-positive. The principal directions of the mandrel are the meridian and the parallel:",
      ],
      ["f", String.raw`k_m=-\frac{r''}{(1+r'^2)^{3/2}},\qquad k_p=\frac{1}{r\sqrt{1+r'^2}}`],
      ["f", String.raw`K=k_mk_p=-\frac{r''}{r\,(1+r'^2)^2},\qquad H=\tfrac12(k_m+k_p)`],
      [
        "p",
        "Euler's formula gives the normal curvature along a yarn at braid angle α (from the meridian):",
      ],
      [
        "f",
        String
          .raw`\kappa_n(\alpha)=k_m\cos^2\alpha+k_p\sin^2\alpha,\qquad \kappa_n<0\iff\alpha<\arctan\sqrt{-k_m/k_p}\ \ (K<0)`,
      ],
      [
        "fig",
        "euler-normal-curvature.svg",
        8,
        "Normal curvature versus braid angle at three points of the default mandrels",
        "On a waist (K < 0) yarns laid below α* would have κn < 0: they bridge.",
      ],
      [
        "fig",
        "gaussian-curvature-profiles.svg",
        9,
        "Gaussian curvature of the default taper, bulge and hourglass",
        "Gaussian curvature in the applet's blue–green–red map (green = 0, each sign scaled by its own extent). Every smooth change of radius has both signs.",
      ],
    ],
  },
  {
    title: "Geodesics (frictionless reference)",
    body: [
      [
        "p",
        "A tensioned yarn on a frictionless surface follows a geodesic. On a surface of revolution geodesics obey Clairaut's relation:",
      ],
      ["f", String.raw`r\sin\alpha=c\quad\Rightarrow\quad \alpha_{geo}(z)=\arcsin\frac{c}{r(z)}`],
      [
        "fig",
        "geodesic-vs-braid.svg",
        10,
        "Braided yarn and geodesic from a common start on the default taper",
        "Where the radius grows the machine raises the braid angle (tan α ≈ ωr/v) but a geodesic lowers it (r sin α = const). The difference is geodesic curvature that friction must supply.",
      ],
    ],
  },
  {
    title: "Mechanics: pressure and slip",
    body: [
      [
        "p",
        "Equilibrium of a flexible yarn with tension T gives the surface reaction per length f = T(κn n − κg b): a line pressure p and a lateral friction demand. With Coulomb friction the laid yarn holds iff",
      ],
      ["f", String.raw`p=T\,\kappa_n,\qquad |\kappa_g|\le\mu\,\kappa_n\quad\text{(no slip)}`],
      [
        "p",
        "By the closed forms, f is parallel to −Ġ⊥ (the part of Ġ normal to the yarn): the guide point must move into the mandrel within the friction cone.",
      ],
      [
        "fig",
        "friction-cone.svg",
        11,
        "No-slip condition as a friction cone in the normal plane of the yarn",
        "Samples: the steady helix on a cylinder (on the cone axis), and two points of the default taper, one of which slips.",
      ],
    ],
  },
  {
    title: "Braid structure",
    body: [
      [
        "p",
        "Pattern m/m: N/m horn gears. Carriers of the two families pass each other on opposite arcs of a gear, and the yarn of the outer carrier goes over. Each gear holds m passings, so every yarn goes over m and under m crossings.",
      ],
      [
        "fig",
        "horn-gear-track.svg",
        12,
        "Horn-gear track of a 16-carrier regular braider at an instant of eight passings",
        "Horn-gear track of a 16-carrier 2/2 machine at an instant when every “+” carrier passes a “−” carrier.",
      ],
      [
        "fig",
        "interlacing-patterns.svg",
        13,
        "Unrolled diamond, regular and Hercules patterns",
        "Unrolled mandrel at α = 45° for 12 carriers; over/under computed from the gear sides.",
      ],
    ],
  },
  {
    title: "Coverage and jamming",
    body: [
      ["p", "Flat yarns of width w, N/2 per direction, at radius r and braid angle α:"],
      [
        "f",
        String
          .raw`k=\frac{N\,w}{4\pi r\cos\alpha},\qquad CF=1-(1-k)^2,\qquad \alpha_{jam}=\arccos\frac{N\,w}{4\pi r}`,
      ],
      ["f", String.raw`\text{triaxial: }CF=1-(1-k)^2(1-k_a),\qquad k_a=\frac{n_a w_a}{2\pi r}`],
      [
        "fig",
        "cover-jamming.svg",
        14,
        "Unit cell of the braid and cover factor versus braid angle",
        "At k = 1 the yarns of one family touch and the braid jams. This is the flat-strip ideal; round yarns jam earlier (CF ≈ 0.82, Zhang et al. 1997).",
      ],
    ],
  },
];

const ASSUMPTIONS = [
  "Yarns are flexible and inextensible, with constant tension and width (no flattening or bending stiffness).",
  "The free yarn is straight from an idealised guide point; there is no friction before contact and no yarn–yarn friction in the convergence zone. Real inter-yarn friction shortens h (about 25 % for 144 carriers, van Ravenhorst & Akkerman 2016).",
  "Deposited yarn sticks. Slip is flagged (|κg| > μκn), not simulated.",
  "Carriers revolve uniformly; horn-gear speed variations are ignored.",
  "Concave stretches and obstacles are bridged by straight chords (flagged). The mandrel is a surface of revolution r(z), so poles and domes are not representable.",
  "Undulation is drawn from the computed crossings; flat tapes may clip slightly near side changes of almost jammed braids.",
];

const REFERENCES = [
  "Kessels J.F.A., Akkerman R. (2002). Prediction of the yarn trajectories on complex braided preforms. Composites Part A 33, 1073–1081. doi:10.1016/S1359-835X(02)00075-1",
  "Du G.-W., Popper P. (1994). Analysis of a circular braiding process for complex shapes. J. Textile Institute 85(3), 316–337. doi:10.1080/00405009408631277",
  "van Ravenhorst J.H., Akkerman R. (2014). Circular braiding take-up speed generation using inverse kinematics. Composites Part A 64, 147–158. doi:10.1016/j.compositesa.2014.04.020",
  "van Ravenhorst J.H., Akkerman R. (2016). A yarn interaction model for circular braiding. Composites Part A 81, 254–263. doi:10.1016/j.compositesa.2015.11.026",
  "Akkerman R., Villa Rodríguez B.H. (2007). Braiding simulation and slip evaluation for arbitrary mandrels. AIP Conf. Proc. 907, 1074–1079. doi:10.1063/1.2729657",
  "Ko F.K. (1987). Braiding. In: Engineered Materials Handbook, Vol. 1, ASM International, 519–528.",
  "Zhang Q., Beale D., Adanur S., Broughton R.M., Walker R.P. (1997). Structural analysis of a two-dimensional braided fabric. J. Textile Institute 88(1), 41–52. doi:10.1080/00405009708658528",
  "Wang R., Jiao W., Liu W., Yang F., He X. (2011). Slippage coefficient measurement for non-geodesic filament-winding process. Composites Part A 42(3), 303–309. doi:10.1016/j.compositesa.2010.12.002",
  "do Carmo M.P. (1976). Differential Geometry of Curves and Surfaces, §4-4 (Clairaut's relation).",
];

/** Live-value rows: [TeX label, unit, getter(ctx) → number | string]. */
const LIVE = [
  [String.raw`t`, "s", (c) => c.sim.time.toFixed(2)],
  [String.raw`z_F`, "mm", (c) => (c.i0.zp * 1e3).toFixed(1)],
  [String.raw`r,\ r'`, "mm, –", (c) => `${(c.e.r * 1e3).toFixed(2)}, ${c.e.dr.toFixed(3)}`],
  [String.raw`h`, "mm", (c) => (c.h * 1e3).toFixed(1)],
  [String.raw`h_{qs}`, "mm", (c) => (c.hqs * 1e3).toFixed(1)],
  [String.raw`L=|G-F|`, "mm", (c) => (c.i0.free * 1e3).toFixed(1)],
  [String.raw`|\alpha|`, "°", (c) => (Math.abs(c.i0.alpha) * DEG).toFixed(2)],
  [String.raw`\alpha_{qs}`, "°", (c) => (c.aqs * DEG).toFixed(2)],
  [String.raw`\kappa_n`, "1/m", (c) => fmt(c.i0.kn)],
  [String.raw`\kappa_g`, "1/m", (c) => fmt(c.i0.kg)],
  [
    String.raw`|\kappa_g/\kappa_n|\ \text{vs}\ \mu`,
    "–",
    (c) =>
      `${fmt(Math.abs(c.i0.slip), 3)} vs ${c.sim.config.friction}${
        Math.abs(c.i0.slip) > c.sim.config.friction ? " (slips)" : ""
      }`,
  ],
  [String.raw`p=T\kappa_n`, "N/m", (c) => fmt(c.sim.config.tension * c.i0.kn)],
  [String.raw`k_m,\ k_p`, "1/m", (c) => `${fmt(c.pr.k_m)}, ${fmt(c.pr.k_p)}`],
  [String.raw`K`, "1/m²", (c) => fmt(c.pr.K)],
  [String.raw`H`, "1/m", (c) => fmt(c.pr.H)],
  [String.raw`r\sin\alpha`, "mm", (c) => fmt(c.e.r * Math.abs(Math.sin(c.i0.alpha)) * 1e3)],
  [String.raw`k,\ CF`, "–", (c) => `${fmt(c.cov.k, 3)}, ${fmt(c.cov.cover, 3)}`],
  [String.raw`\alpha_{jam}`, "°", (c) => (c.ajam * DEG).toFixed(1)],
  [String.raw`\text{state}`, "", (c) => c.sim.mode[c.k]],
];

function fmt(v, d = 2) {
  if (!Number.isFinite(v)) return "–";
  const a = Math.abs(v);
  return a !== 0 && (a >= 1e5 || a < 1e-3) ? v.toExponential(2) : v.toFixed(d);
}

/**
 * A figure with caption; the image links to the full-size SVG (the side panel is narrow).
 * @returns {HTMLElement}
 */
function figure(file, number, alt, caption) {
  const fig = document.createElement("figure");
  fig.className = "theory-fig";
  const a = document.createElement("a");
  a.href = FIGURE_DIR + file;
  a.target = "_blank";
  a.rel = "noopener";
  a.title = "Open full size";
  const img = document.createElement("img");
  img.src = FIGURE_DIR + file;
  img.alt = alt;
  img.loading = "lazy";
  a.appendChild(img);
  const cap = document.createElement("figcaption");
  const b = document.createElement("b");
  b.textContent = `Figure ${number}. `;
  cap.append(b, caption);
  fig.append(a, cap);
  return fig;
}

export class TheoryPanel {
  /** @param {HTMLElement} host */
  constructor(host) {
    this.host = host;
    const h = (tag, text, cls) => {
      const el = document.createElement(tag);
      if (text) el.textContent = text;
      if (cls) el.className = cls;
      host.appendChild(el);
      return el;
    };
    h("h2", "Live values at the selected fell point");
    this.sel = h("p", "", "note");
    const table = h("table", "", "live-table");
    this.cells = LIVE.map(([tex, unit]) => {
      const tr = document.createElement("tr");
      const l = document.createElement("td"),
        v = document.createElement("td"),
        u = document.createElement("td");
      katex.render(tex, l, { throwOnError: false });
      v.className = "v";
      u.className = "u";
      u.textContent = unit;
      tr.append(l, v, u);
      table.appendChild(tr);
      return v;
    });
    for (const s of SECTIONS) {
      h("h2", s.title);
      for (const [kind, ...payload] of s.body) {
        if (kind === "p") h("p", payload[0]);
        else if (kind === "fig") host.appendChild(figure(...payload));
        else {
          const div = h("div", "", "formula");
          katex.render(payload[0], div, { displayMode: true, throwOnError: false });
        }
      }
    }
    h("h2", "Assumptions and limitations");
    const ul = h("ul");
    for (const a of ASSUMPTIONS) {
      const li = document.createElement("li");
      li.textContent = a;
      ul.appendChild(li);
    }
    h("h2", "References");
    const ol = h("ol");
    for (const r of REFERENCES) {
      const li = document.createElement("li");
      li.textContent = r;
      li.className = "note";
      ol.appendChild(li);
    }
    const more = h("p", "", "note");
    const doc = document.createElement("a");
    doc.href = THEORY_URL;
    doc.target = "_blank";
    doc.rel = "noopener";
    doc.textContent = "docs/THEORY.md";
    more.append("Full derivations: ", doc, ". Click a figure to open it at full size.");
    this.selected = 0;
  }

  reset(sim, display) {
    this.selected = display.selectedYarn;
    this.update(sim);
  }

  onSelect(k) {
    this.selected = k;
  }

  show(sim) {
    if (sim) this.update(sim);
  }

  update(sim) {
    const k = Math.min(this.selected, sim.yarns.length - 1), y = sim.yarns[k];
    const i0 = y.get(y.last);
    const c = sim.config, prof = sim.profile;
    const e = prof.evaluate(i0.zp);
    const cov = coverFactor({
      carriers: c.carriers,
      width: c.yarnWidth,
      r: e.r,
      alpha: Math.abs(i0.alpha),
    });
    const ctx = {
      sim,
      k,
      i0,
      e,
      pr: sim.surface.principal(i0.zp),
      h: sim.convergenceLength(sim.fell[k], sim.time),
      hqs: quasiStaticConvergenceLength(prof, i0.zp, c.omega, c.takeUp, c.ringRadius),
      aqs: quasiStaticAngle(prof, i0.zp, c.omega, c.takeUp),
      cov,
      ajam: jammingAngle(c.carriers, c.yarnWidth, e.r),
    };
    this.sel.textContent = `${y.family === 1 ? "+" : "−"} family, carrier ${y.index}` +
      (i0.flags & 1 ? " (still at the tie point: no yarn deposited yet)" : "");
    LIVE.forEach(([, , get], j) => (this.cells[j].textContent = String(get(ctx))));
  }
}
